travis:
  secure:
    BINSTAR_TOKEN: XETW6s6PnH/091yCRtK3T4YPr+EI2GVMacS6D+dC+FxDMT5OTJ3lDxfrHi3EXrgbFMbMJjv8Rfk0NH4BA9VrxdHe7Rp0LQiXzxvpyNLFN1kXzKj7HGoi9Q4qsCLxC2UQZz3rNxWzDZOpt8Uykus/mbUrt737GSnzHCwZRE/2V1i2QQbwabJ0Ipx4NQDmr7eGHhVVqHreda/YxcT5Y79IKrfs7A5elNYBaPLv+MiXuJjM/59t9P6VhdumxejeyOaZi36gYJG+lkR1MWjjGJWWH2xP5DlZh65JNNWMSasZBf8i4t4be2h9bqNZVpdictEBuFkMMb2U9nRI08+ryp8I7b/Celo/4SnjowtOOFili6AyAooilTPv+WfRPBostdYS60ycNxPzD5OUFpKAEIpcIQ1ox6xdfkaj1pUWIP7+Gw+PtmODCuY/WNoz0Ioee26yF3w8kramrCrqk5VtlwmJpBCkh3TyvpG7+scKY/cVcMQ/iN7q0kOekocdkv7MyvKRU1Ttzw79WnKIvDVH6iRb3yEIXQ342ObDfEXsrYBNQHPjJpujHJ7kYKTW4vBv0E4HbQuR9Tnc8ZLPc/92yWZVTgyL3C8cwry6+mtif//ltIger8N/IDuQZLzw6ahkeHPPK8KX5Pn/dibGVMjnCOnBdURQyU/bq4Jj9NXsRjeRmxQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
